[project]
name = "odoo-addons-oca-stock-weighing"
version = "18.0.20260621.0"
dependencies = [
    "odoo-addon-mrp_weighing==18.0.*",
    "odoo-addon-partner_delivery_zone_weighing==18.0.*",
    "odoo-addon-sale_elaboration_weighing==18.0.*",
    "odoo-addon-sale_stock_weighing==18.0.*",
    "odoo-addon-stock_remote_measure==18.0.*",
    "odoo-addon-stock_weighing==18.0.*",
    "odoo-addon-stock_weighing_auto_create_lot==18.0.*",
    "odoo-addon-stock_weighing_auto_package==18.0.*",
    "odoo-addon-stock_weighing_brand==18.0.*",
    "odoo-addon-stock_weighing_remote_measure==18.0.*",
    "odoo-addon-web_widget_remote_measure==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
